version: "3"

services:
  fullstack-test:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: "fullstack-test"
    restart: always
    volumes:
      - ./fullstack-test-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass

volumes:
  fullstack-test-vol: